GO := go
GOFMT := gofmt
ARCH ?= $(shell go env GOARCH)
OS ?= $(shell go env GOOS)

.PHONY: all

IMAGE_REPOSITORY_URL = registry.wanzhixin.net/fanli/order
BUILD_NUMBER = $(shell git rev-parse --short HEAD)
ifneq ($(CI_COMMIT_BRANCH),)
	ifeq ($(CI_COMMIT_BRANCH),master)
		BUILD_TAG := $(shell date +%Y%m%d%H%M%S)
	else
		BUILD_TAG := $(CI_COMMIT_BRANCH)
	endif
else
	ifeq ($(CI_COMMIT_TAG),)
		BUILD_TAG := $(shell date +%Y%m%d%H%M%S)
	else
		BUILD_TAG := $(CI_COMMIT_TAG)
	endif
endif
COMMAND_ROOT = dev-gitlab.wanxingrowth.com/fanli/order/v2/cmd

ifneq ($(shell uname), Darwin)
	EXTLDFLAGS = -extldflags "-static" $(null)
else
	EXTLDFLAGS =
endif

all: build test

build: build_service_cross_only

.PHONY: restful_doc

SED_PATH := $(shell which sed)
restful_doc:
	# swaggo need larger than 1.6
	swag init -g cmd/main.go -o pkg/restful/swaggerdocs
	if strings $(SED_PATH) | grep -q 'GNU'; then \
		$(SED_PATH) -i '/^\/\/ This file was generated by swaggo\/swag at/{n;d;}' pkg/restful/swaggerdocs/docs.go; \
		$(SED_PATH) -i '/^\/\/ This file was generated by swaggo\/swag at/d' pkg/restful/swaggerdocs/docs.go; \
	else \
		$(SED_PATH) -i '' '/^\/\/ This file was generated by swaggo\/swag at/{n;d;}' pkg/restful/swaggerdocs/docs.go; \
		$(SED_PATH) -i '' '/^\/\/ This file was generated by swaggo\/swag at/d' pkg/restful/swaggerdocs/docs.go; \
	fi

.PHONY: test
test:
	mkdir -p .test-result
	go test -cover -coverprofile cover.out -outputdir .test-result ./...
	go tool cover -html=.test-result/cover.out -o .test-result/coverage.html

.PHONY: build_service_local
build_service_local: build_service_protos restful_doc
	mkdir -p builds/debug
	go build -o builds/debug/service -ldflags '${EXTLDFLAGS}-X dev-gitlab.wanxingrowth.com/wanxin-go-micro/base/utils/version.VersionDev=build.$(BUILD_NUMBER)' $(COMMAND_ROOT)

.PHONY: build_service_cross
build_service_cross: build_service_protos restful_doc
	mkdir -p builds/release
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o builds/release/service -ldflags '${EXTLDFLAGS}-X dev-gitlab.wanxingrowth.com/wanxin-go-micro/base/utils/version.VersionDev=build.$(BUILD_NUMBER)' $(COMMAND_ROOT)

.PHONY: build_service_cross_only
build_service_cross_only:
	mkdir -p builds/release
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o builds/release/service -ldflags '${EXTLDFLAGS}-X dev-gitlab.wanxingrowth.com/wanxin-go-micro/base/utils/version.VersionDev=build.$(BUILD_NUMBER)' $(COMMAND_ROOT)

.PHONY: run_service_local
run_service_local: build_service_local
	# Use ./config/example.yaml copy to ./config/dev.yaml when first time debug
	builds/debug/service --config=./config/dev.yaml

build_service_image:
	docker build -t $(IMAGE_REPOSITORY_URL):$(BUILD_TAG) -f builds/docker/Dockerfile .

push_service_image: build_service_image
	docker push $(IMAGE_REPOSITORY_URL):$(BUILD_TAG)

push_service_image_clear_local: push_service_image
	docker rmi $(IMAGE_REPOSITORY_URL):$(BUILD_TAG)

push_service_image_clear_local_write_url: push_service_image_clear_local
	echo "$(IMAGE_REPOSITORY_URL):$(BUILD_TAG)" > builds/docker/latest-image

.PHONY: build_service_protos
build_service_protos:
	@sh builds/protos/protos.sh

.PHONY: pre_commit
pre_commit: test
	go fmt ./...
	go vet ./...
