host: localhost:8080
info:
  contact:
    email: huangyichao@wanxingrowth.com
    name: Luckyboys
    url: http://dev-gitlab.wanxingrowth.com/fanli/order/v2/issues
  description: The framework use for init new service.
  license: {}
  title: wanxin-blank-service
  version: "0.1"
paths: {}
swagger: "2.0"
