// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	common.proto
	merchant_freight.proto
	order.proto
	state.proto

It has these top-level messages:
	Error
	GetMerchantFreightRequest
	GetMerchantFreightReply
	MerchantFreightSetting
	SetMerchantFreightRequest
	SetMerchantFreightReply
	CreateOrderRequest
	CreateOrderReply
	CreateOrderGoods
	Attribute
	CreateOrderDiscount
	Address
	Order
	Logistics
	Goods
	Discount
	Payment
	StatusModificationLog
	Comment
	OrderDetailsRequest
	OrderDetailsReply
	CancelOrderRequest
	CancelOrderReply
	PaidOrderRequest
	PaidOrderReply
	DeliverOrderRequest
	DeliverOrderReply
	DeliveryPackage
	ChangeRefundStatusRequest
	ChangeRefundStatusReply
	CommentOrderRequest
	CommentOrderReply
	CommentGoods
	GetOrderListRequest
	TimeRange
	GetOrderListReply
	ReceivedOrderRequest
	ReceivedOrderReply
	PingRequest
	PingReply
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 错误信息
type Error struct {
	// 错误码
	ErrorCode uint32 `protobuf:"varint,1,opt,name=errorCode" json:"errorCode,omitempty"`
	// 展示给开发这记录日志用的错误信息
	ErrorMessageForDeveloper string `protobuf:"bytes,2,opt,name=errorMessageForDeveloper" json:"errorMessageForDeveloper,omitempty"`
	// 展示给用户查看的错误信息
	ErrorMessageForUser string `protobuf:"bytes,3,opt,name=errorMessageForUser" json:"errorMessageForUser,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Error) GetErrorMessageForDeveloper() string {
	if m != nil {
		return m.ErrorMessageForDeveloper
	}
	return ""
}

func (m *Error) GetErrorMessageForUser() string {
	if m != nil {
		return m.ErrorMessageForUser
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "protos.Error")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0x93, 0x19,
	0xb9, 0x58, 0x5d, 0x8b, 0x8a, 0xf2, 0x8b, 0x84, 0x64, 0xb8, 0x38, 0x53, 0x41, 0x0c, 0xe7, 0xfc,
	0x94, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xde, 0x20, 0x84, 0x80, 0x90, 0x15, 0x97, 0x04, 0x98,
	0xe3, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0xea, 0x96, 0x5f, 0xe4, 0x92, 0x5a, 0x96, 0x9a, 0x93,
	0x5f, 0x90, 0x5a, 0x24, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x84, 0x53, 0x5e, 0xc8, 0x80, 0x4b,
	0x18, 0x4d, 0x2e, 0xb4, 0x38, 0xb5, 0x48, 0x82, 0x19, 0xac, 0x0d, 0x9b, 0x54, 0x12, 0xc4, 0x75,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x29, 0x17, 0x60, 0xde, 0xb4, 0x00, 0x00, 0x00,
}
